### ISSUE TITLE
Powershell doesn't load PSDecode module ,how to fix it?

### ISSUE THREAD

**Issue by hekkoav** [R3MRUM/PSDecode#1]
Changed  signature policy.  "set-ExecutionPolicy RemoteSigned "

**Comment by R3MRUM** [comment]
Added a 2nd note in the README regarding how to address this error. Basically you need to use the **Unrestricted** execution policy and not **RemoteSigned**. This is because PSDecode isn't a signed application. Let me know if this doesn't fix your issue. If you still get errors, it will help if you include the full error output that you are receiving.

Here is another blog post that could also assist:
https://www.cogmotive.com/blog/powershell/allowing-powershell-scripts-to-execute
